{
 "title": "Docker Prometheus Monitoring 2 Copy",
 "description": "Docker Monitoring Template",
 "time": { "from": "2023-01-25T22:38:47.974Z", "to": "2023-01-25T23:22:25.842Z" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "IP",
    "query": {
     "query": "label_values(node_exporter_build_info{name=~'$name'},instance)"
    }
   },
   {
    "name": "env",
    "label": "Env",
    "query": {
     "query": "label_values(node_exporter_build_info,env)"
    }
   },
   {
    "name": "name",
    "label": "CPU Name",
    "query": {
     "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Paxos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Paxos Retries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(paxos_requests_finished_bytes_sum[$interval])",
     "legendFormat": "Goodput"
    },
    {
     "expr": "rate(paxos_requests_sent_bytes_sum[$interval])",
     "legendFormat": "Incoming Throughput"
    },
    { "expr": "paxos_batch_size", "legendFormat": "batch" },
    {
     "expr": "rate(paxos_request_retries_total[$interval]) ",
     "legendFormat": "retries"
    },
    {
     "expr": "rate(paxos_request_retry_completed_total[$interval])",
     "legendFormat": "Completed Retries"
    },
    {
     "expr": "(sum by (node) (rate(container_network_receive_bytes_total{image!=\"\", name=\"postgres_service\"}[$interval] ) ))",
     "legendFormat": "postgres network-{{node}}"
    }
   ]
  },
  {
   "title": "Postgres network ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(paxos_requests_finished_bytes_sum[$interval])",
     "legendFormat": "Goodput"
    },
    {
     "expr": "rate(paxos_requests_sent_bytes_sum[$interval])",
     "legendFormat": "Incoming Throughput"
    },
    { "expr": "paxos_batch_size", "legendFormat": "batch" },
    {
     "expr": "sum by (node) (rate(container_network_receive_bytes_total{image!=\"\", name=\"postgres_service\"} [$interval]) + rate(container_network_transmit_bytes_total{image!=\"\", name=\"postgres_service\"} [$interval]))",
     "legendFormat": "postgres network-{{node}}"
    }
   ]
  },
  {
   "title": "Postgres network seperate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(paxos_requests_finished_bytes_sum[$interval])",
     "legendFormat": "Goodput"
    },
    {
     "expr": "rate(paxos_requests_sent_bytes_sum[$interval])",
     "legendFormat": "Incoming Throughput"
    },
    { "expr": "paxos_batch_size", "legendFormat": "batch" },
    {
     "expr": "rate(container_network_receive_bytes_total{image!=\"\", name=\"postgres_service\"}[$interval])",
     "legendFormat": "postgres network recieve  {{node}}"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total{image!=\"\", name=\"postgres_service\"}[$interval])",
     "legendFormat": "postgres network transmit  {{node}}"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(paxos_requests_finished_bytes_sum[$interval])",
     "legendFormat": "Goodput"
    },
    {
     "expr": "rate(paxos_requests_sent_bytes_sum[$interval])",
     "legendFormat": "Incoming Throughput"
    },
    {
     "expr": "(100 - (avg(irate(node_cpu_seconds_total{node!=\"client\", mode=\"idle\"}[$interval])) by (node) * 100)) > 0 \n",
     "legendFormat": "Average CPU Usage {{node}}"
    }
   ]
  },
  {
   "title": "Postgres CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(paxos_requests_finished_bytes_sum[$interval])",
     "legendFormat": "Goodput"
    },
    {
     "expr": "rate(paxos_requests_sent_bytes_sum[$interval])",
     "legendFormat": "Incoming Throughput"
    },
    { "expr": "paxos_batch_size", "legendFormat": "batch" },
    {
     "expr": "(avg(irate(container_cpu_usage_seconds_total{image!=\"\", name=\"postgres_service\"}[1m])) by (node)) * 100",
     "legendFormat": "CPU Usage Postgres - {{ node }}"
    }
   ]
  },
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(paxos_requests_finished_bytes_sum[$interval])",
     "legendFormat": "Goodput"
    },
    {
     "expr": "rate(paxos_requests_sent_bytes_sum[$interval])",
     "legendFormat": "Incoming Throughput"
    },
    { "expr": "paxos_batch_size", "legendFormat": "batch" },
    {
     "expr": "(sum(node_memory_MemTotal_bytes{node!=\"client\"}) by (node)) - (sum(node_memory_MemAvailable_bytes{node!=\"client\"}) by (node))",
     "legendFormat": "Memory Usage ({{node}})"
    }
   ]
  },
  {
   "title": "Postgres Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(paxos_requests_finished_bytes_sum[$interval])",
     "legendFormat": "Goodput"
    },
    {
     "expr": "rate(paxos_requests_sent_bytes_sum[$interval])",
     "legendFormat": "Incoming Throughput"
    },
    { "expr": "paxos_batch_size", "legendFormat": "batch" },
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\", name=\"postgres_service\"}",
     "legendFormat": "Postgres Memory Usage ({{node}})"
    }
   ]
  },
  {
   "title": "Host Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(ALERTS)" }
   ]
  },
  {
   "title": "Targets Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(up)" }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{job=\"cadvisor\", name!=\"\"}[5m]))"
    }
   ]
  },
  {
   "title": "Host Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes +node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[2s])) * 100)"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg( node_filesystem_avail_bytes {mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Node Network Traffic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "RECEIVE"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
     "legendFormat": "TRANSMIT"
    }
   ]
  },
  {
   "title": "Node Mermory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes) - sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Available Memory"
    }
   ]
  },
  {
   "title": "Filesystem Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes {job=\"node-exporter\", instance=~\".*9100\", device=~\"/dev/.*\", mountpoint!=\"/var/lib/docker/aufs\"}) ",
     "legendFormat": "Free Storage"
    }
   ]
  },
  {
   "title": "Container Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (id,name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Output",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_transmit_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Container Network Input",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(sum by (name) (rate(container_network_receive_bytes_total{image!=\"\"}[1m] ) ))",
     "legendFormat": "{{ name }}"
    }
   ]
  }
 ]
}