CREATE TABLE IF NOT EXISTS data1 (key VARCHAR(255) PRIMARY KEY, value VARCHAR(255));
CREATE TABLE IF NOT EXISTS data2 (key VARCHAR(255) PRIMARY KEY, value VARCHAR(255));
CREATE TABLE IF NOT EXISTS data3 (key VARCHAR(255) PRIMARY KEY, value VARCHAR(255));