all:
  children:
    
    server1:
      hosts:
        129.114.109.177:
          ansible_user: "cc"
          ansible_connection: ssh

      vars:
        port: 8001
        discovery_ip: 10.52.3.170
        postgres: 9000
        partition: 1
  
    server2:
      hosts:
        129.114.109.100:
          ansible_user: "cc"
          ansible_connection: ssh

      vars:
        port: 8002
        discovery_ip: 10.52.0.31
        postgres: 9000
        partition: 2


    server3:
      hosts:
        129.114.108.193:
          ansible_user: "cc"
          ansible_connection: ssh

      vars:
        port: 8003
        discovery_ip: 10.52.0.245
        postgres: 9000
        partition: 3

    client:
      hosts:
        129.114.109.169:
          ansible_user: "cc"
          ansible_connection: ssh