all:
  children:
    servers:
        hosts:
          129.114.108.150:
            ansible_user: "cc"
            ansible_connection: ssh
            port: 8001
            discovery_ip: 10.52.2.64
            postgres: 9000
            partition: 1

          129.114.109.89:
            ansible_user: "cc"
            ansible_connection: ssh
            port: 8002
            discovery_ip: 10.52.3.101
            postgres: 9000
            partition: 2

          129.114.109.11:
            ansible_user: "cc"
            ansible_connection: ssh
            port: 8003
            discovery_ip: 10.52.3.217
            postgres: 9000
            partition: 3

    client:
      hosts:
        129.114.108.121:
          ansible_user: "cc"
          ansible_connection: ssh