all:
  children:
    
    server1:
      hosts:
        129.114.109.1:
          ansible_user: "cc"
          ansible_connection: ssh

      vars:
        port: 8001
        postgres: 9000
        partition: 1
  
    server2:
      hosts:
        129.114.109.112:
          ansible_user: "cc"
          ansible_connection: ssh

      vars:
        port: 8002
        postgres: 9000
        partition: 2


    server3:
      hosts:
        129.114.108.105:
          ansible_user: "cc"
          ansible_connection: ssh

      vars:
        port: 8003
        postgres: 9000
        partition: 3

    client:
      hosts:
        129.114.108.225:
          ansible_user: "cc"
          ansible_connection: ssh