---
- name: Install Requirements (Java, Docker) on servers
  hosts:
    - servers
  become: yes
  tasks:
    - include_role:
        name: common
        tasks_from: install_docker.yml
    - include_role:
        name: common
        tasks_from: install_java.yml

- name: Install Requirements (Java) on client
  hosts:
    - client
  become: yes
  tasks:
    - include_role:
        name: common
        tasks_from: install_docker.yml
    - include_role:
        name: common
        tasks_from: install_java.yml
